config/routes.rb
Rails.application.routes.draw do


  get 'makker/heading' =>'images_makker#heading'

  get 'makker/paragraph'=>'images_makker#paragraph'

  get 'makker/create'=>'images_makker#create'

  get 'images/create'

  get 'user/index'

  get 'user/myvideos'
  get 'admin/index'

  get 'user/video/' =>'user#myvideos'

  get 'user/video/article' =>'article#index'
  get 'user/video/article/scrap' =>'article#scrap'

  devise_for :users
  get 'home/index'
  get 'home/indexjson'


  root 'home#index'

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
    get 'signin' => 'devise/sessions#new'
    post 'signin' => 'devise/sessions#create'

  end
  end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsProject</title>
  <%= csrf_meta_tags %>
</head>
<body>
<% if(user_signed_in?) %>

  <td><%= link_to 'Sign out', '/users/sign_out' , method: :delete, data: { confirm: 'Are you sure to Sign Out?' } %></td>
    <td><%= link_to 'User Panel', '/user/index'  %></td>

<% else %>
  <td><%= link_to 'Sign In', '/users/sign_in' %></td>
<% end %>
<p id="notice"><%= notice %></p>

<%= yield %>

</body>
</html>

app/views/layouts/application.html_2.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if(user_signed_in?) %>

  <td><%= link_to 'Sign out', '/users/sign_out' , method: :delete, data: { confirm: 'Are you sure to Sign Out?' } %></td>
  <td><%= link_to 'Tasks', '/tasks' %></td>

<% else %>
  <td><%= link_to 'Sign In', '/users/sign_in' %></td>
<% end %>
<p id="notice"><%= notice %></p>

<%= yield %>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 2 | Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.5 -->
  <link rel="stylesheet" href="/back/bootstrap/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/back/bootstrap/css/ionicons.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="/back/bootstrap/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/back/dist/css/AdminLTE.min.css">
  <!-- iCheck -->
  <link rel="stylesheet" href="/back/plugins/iCheck/square/blue.css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!-- jQuery 2.1.4 -->
  <script src="/back/plugins/jQuery/jQuery-2.1.4.min.js"></script>
  <!-- Bootstrap 3.3.5 -->
  <script src="/back/bootstrap/js/bootstrap.min.js"></script>

  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->


</head>
<body class="hold-transition login-page">

<%= yield%>



<!-- iCheck -->
<script src="/back/plugins/iCheck/icheck.min.js"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' // optional
    });
  });
</script>
</body>
</html>

app/views/layouts/front.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if(user_signed_in?) %>

  <td><%= link_to 'Sign out', '/users/sign_out' , method: :delete, data: { confirm: 'Are you sure to Sign Out?' } %></td>
  <td><%= link_to 'Tasks', '/tasks' %></td>

<% else %>
  <td><%= link_to 'Sign In', '/users/sign_in' %></td>
<% end %>
<p id="notice"><%= notice %></p>

<%= yield %>

</body>
</html>

app/views/layouts/userpanel.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Article Video Robot</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="/back/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <!-- DataTables -->
    <link rel="stylesheet" href="/back/plugins/datatables/dataTables.bootstrap.css">
    <link rel="stylesheet" href="/back/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/back/dist/css/skins/_all-skins.min.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- end Modals-->
    <script src="/back/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="/back/js/jquery-ui.min.js"></script>
    <script src="/back/js/modal.js"></script>


  </head>
  <body class="hold-transition skin-blue sidebar-mini">

    <!-- Site wrapper -->
    <div class="wrapper">

      <header class="main-header">
        <!-- Logo -->
        <a href="/" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>A</b>VR</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>ArticleVideoRobot</b>New</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- Messages: style can be found in dropdown.less-->
              <li class="dropdown messages-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-envelope-o"></i>
                  <span class="label label-success">4</span>
                </a>
                <ul class="dropdown-menu">
                  <li class="header">You have 4 messages</li>
                  <li>
                    <!-- inner menu: contains the actual data -->
                    <ul class="menu">
                      <li><!-- start message -->
                        <a href="#">
                          <div class="pull-left">
                            <img src="/back/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                          </div>
                          <h4>
                            Support Team
                            <small><i class="fa fa-clock-o"></i> 5 mins</small>
                          </h4>
                          <p>Why not buy a new awesome theme?</p>
                        </a>
                      </li><!-- end message -->
                    </ul>
                  </li>
                  <li class="footer"><a href="#">See All Messages</a></li>
                </ul>
              </li>
              <!-- Notifications: style can be found in dropdown.less -->
              <li class="dropdown notifications-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-bell-o"></i>
                  <span class="label label-warning">10</span>
                </a>
                <ul class="dropdown-menu">
                  <li class="header">You have 10 notifications</li>
                  <li>
                    <!-- inner menu: contains the actual data -->
                    <ul class="menu">
                      <li>
                        <a href="#">
                          <i class="fa fa-users text-aqua"></i> 5 new members joined today
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li class="footer"><a href="#">View all</a></li>
                </ul>
              </li>
              <!-- Tasks: style can be found in dropdown.less -->
              <li class="dropdown tasks-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-flag-o"></i>
                  <span class="label label-danger">9</span>
                </a>
                <ul class="dropdown-menu">
                  <li class="header">You have 9 tasks</li>
                  <li>
                    <!-- inner menu: contains the actual data -->
                    <ul class="menu">
                      <li><!-- Task item -->
                        <a href="#">
                          <h3>
                            Design some buttons
                            <small class="pull-right">20%</small>
                          </h3>
                          <div class="progress xs">
                            <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">20% Complete</span>
                            </div>
                          </div>
                        </a>
                      </li><!-- end task item -->
                    </ul>
                  </li>
                  <li class="footer">
                    <a href="#">View all tasks</a>
                  </li>
                </ul>
              </li>
              <!-- User Account: style can be found in dropdown.less -->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <img src="/back/dist/img/user2-160x160.jpg" class="user-image" alt="User Image">
                  <span class="hidden-xs">Alexander Pierce</span>
                </a>
                <ul class="dropdown-menu">
                  <!-- User image -->
                  <li class="user-header">
                    <img src="/back/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                    <p>
                      Alexander Pierce - Web Developer
                      <small>Member since Nov. 2012</small>
                    </p>
                  </li>
                  <!-- Menu Body -->
                  <li class="user-body">
                    <div class="col-xs-12 text-center">

                      <a class="btn btn-block btn-social btn-twitter">
                        <i class="ion ion-ios-cart-outline"></i> Upgrade
                      </a>
                  </li>
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-left">
                      <a href="#" class="btn btn-default btn-flat">Profile</a>
                    </div>
                    <div class="pull-right">
                      <a href="/users/sign_out" class="btn btn-default btn-flat">Sign out</a>
                    </div>
                  </li>
                </ul>
              </li>
              <!-- Control Sidebar Toggle Button -->

            </ul>
          </div>
        </nav>
      </header>

      <!-- =============================================== -->

      <!-- Left side column. contains the sidebar -->
      <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar user panel -->
          <div class="user-panel">
            <div class="pull-left image">
              <img src="/back/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
              <p>Alexander Pierce</p>
              <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
          </div>
          <!-- search form -->
          <!-- /.search form -->
          <!-- sidebar menu: : style can be found in sidebar.less -->
          <ul class="sidebar-menu">
            <li class="header">MAIN NAVIGATION</li>
            <li class="treeview <% if controller.controller_name == "user" && controller.action_name == "index" %>active<%end%>">
              <a href="<%=user_index_path%>">
                <i class="fa fa-dashboard"></i> <span>Dashboard</span>
              </a>

            </li>
            <li class="treeview <% if controller.controller_name == "user" && controller.action_name == "myvideos" %>active<%end%>">
              <a href="<%=user_myvideos_path%>">
                <i class="fa  fa-video-camera"></i> <span>My Videos</span>
              </a>

            </li>
            <li class="header">Help</li>
            <li class="treeview <% if controller.controller_name == "user" && controller.action_name == "myproject" %>active<%end%>">
              <a href="<%=user_index_path%>">
                <i class="fa  fa-play-circle"></i> <span>Video Tutorials</span>
              </a>

            </li>
            <li class="treeview <% if controller.controller_name == "user" && controller.action_name == "myproject" %>active<%end%>">
              <a href="<%=user_index_path%>">
                <i class="fa fa-book"></i> <span  >Help Manual</span>
              </a>

            </li>
            <li class="treeview <% if controller.controller_name == "user" && controller.action_name == "myproject" %>active<%end%>">
              <a href="<%=user_index_path%>">
                <i class="fa  fa-puzzle-piece"></i> <span>Support Desk</span>
              </a>

            </li>


          </ul>
        </section>
        <!-- /.sidebar -->
      </aside>

      <!-- =============================================== -->

      <!-- Content Wrapper. Contains page content -->


        <%=yield%>


      <footer class="main-footer">
        <div class="pull-right hidden-xs">
          <b>Version</b> 2.3.0
        </div>
        <strong>Copyright &copy; 2014-2015 <a href="<%=home_index_url%>">Article Video Robot</a>.</strong> All rights reserved.
      </footer>

      <!-- Control Sidebar -->
      <!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
    </div><!-- ./wrapper -->
    <!-- Modals-->

    <div id="modal_" class="modal fade" role="dialog">
      <div class="modal-dialog">
        <!-- Modal content-->

        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close btn_modal_close"   >&times;</button>
            <h4 class="modal-title" id="modal_title"></h4>
          </div>
          <div class="modal-body" id="modal_body">



          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default btn_modal_close" >Close</button>
          </div>
        </div>

      </div>
    </div>


    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.5 -->
    <script src="/back/bootstrap/js/bootstrap.min.js"></script>
    <!-- Morris.js charts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="/back/plugins/morris/morris.min.js"></script>
    <!-- Sparkline -->
    <script src="/back/plugins/sparkline/jquery.sparkline.min.js"></script>
    <!-- jvectormap -->
    <script src="/back/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="/back/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="/back/plugins/knob/jquery.knob.js"></script>
    <!-- daterangepicker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js"></script>
    <script src="/back/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- datepicker -->
    <script src="/back/plugins/datepicker/bootstrap-datepicker.js"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="/back/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>


    <script src="/back/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="/back/plugins/datatables/dataTables.bootstrap.min.js"></script>


    <!-- Slimscroll -->
    <script src="/back/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="/back/plugins/fastclick/fastclick.js"></script>


    <!-- AdminLTE App -->
    <script src="/back/dist/js/app.min.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="/back/dist/js/pages/dashboard.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/back/dist/js/demo.js"></script>


  </body>
</html>